### ISSUE TITLE
ZXing barcode scanner on iOS won't read barcodes

### ISSUE THREAD

**Issue by P-AOT** [nblockchain/ZXing.Net.Xamarin#5]
I'm working Sample.Forms and select target on IOS.
OnScanResult event is never fired. I have tested with Iphone device (software version 14.0.1) 
But the Android device it's working fine.

**Comment by knocte** [comment]
What version of ZXing.Net.Xamarin are you using? Did you test with ZXing.Net.Mobile?

**Comment by Pleart1** [comment]
i'm not using ZXing.Net.Xamarin. I have Included the project that I download from your master branch on github.
 

 <ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="4.5.0.356" />
    <PackageReference Include="Xamarin.Essentials" Version="1.5.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\ZXing.Net.Mobile.Forms\ZXing.Net.Mobile.Forms.csproj">
      <Project>{bc6f43c4-0ffa-487b-b74f-b26a8c8b3809}</Project>
      <Name>ZXing.Net.Mobile.Forms</Name>
    </ProjectReference>
    <ProjectReference Include="..\..\..\ZXing.Net.Mobile\ZXing.Net.Mobile.csproj">
      <Project>{8b7a8ab6-35a4-4c9c-83e1-96ba8be3c941}</Project>
      <Name>ZXing.Net.Mobile</Name>
    </ProjectReference>
    <ProjectReference Include="..\Sample.Forms\Sample.Forms.csproj">
      <Project>{cdf8aa59-65ab-4f2c-8de0-d9d13f84e854}</Project>
      <Name>Sample.Forms</Name>
    </ProjectReference>
  </ItemGroup>
  <Import Project="$(MSBuildExtensionsPath)\Xamarin\iOS\Xamarin.iOS.CSharp.targets" />

**Comment by P-AOT** [comment]
i'm not using ZXing.Net.Xamarin. I have Included the project that I download from your master branch on github.

![freesnippingtool com_capture_20200929155911](https://user-images.githubusercontent.com/72060804/94536317-d51b6d00-026c-11eb-8254-af535b462a4c.png)

**Comment by knocte** [comment]
> i'm not using ZXing.Net.Xamarin

what? then why do you file the bug here?

> I have Included the project that I download from your master branch on github.

Then you are using ZXing.Net.Xamarin.

However, do you know the difference between ZXing.Net.Xamarin and ZXing.Net.Mobile? If you don't, then you should use ZXing.Net.Mobile instead. ZXing.Net.Xamarin is a very specific fork.

**Comment by P-AOT** [comment]
Sorry i misunderstood. Thank you for your help.
