### ISSUE TITLE
Qr scan and the flash command don't work in iOS (but they work in Android in my Xamarin Forms project)

### ISSUE THREAD

**Issue by AndreaGobs** [nblockchain/ZXing.Net.Xamarin#6]
Below is the working code for an Android QR scanner, the only property I set is the format to QR_CODE. In iOS I tried different combinations of AutoRotate, TryHarder, TryInverted, DelayBetweenContinuousScans and DelayBetweenAnalyzingFrames but with no result. Removing the QR_CODE format from options, iOS is able to scan eg EAN_13 but never QR_CODE.

Page view:
```
<Grid>
	<zxing:ZXingScannerView x:Name="zxing"
		HorizontalOptions="FillAndExpand"
		VerticalOptions="FillAndExpand"
		OnScanResult="zxing_OnScanResult"/>
	<zxing:ZXingDefaultOverlay x:Name="overlay"
		TopText = "Hold your phone up to the barcode"
		BottomText = "Scanning will happen automatically"
		ShowFlashButton="True"
		FlashButtonClicked="overlay_FlashButtonClicked"/>
</Grid>
```

Page code:
```
[XamlCompilation(XamlCompilationOptions.Compile)]
public partial class PageScan : ContentPage
{
	public PageScan()
	{
		InitializeComponent();
	}

	protected override void OnAppearing()
	{
		base.OnAppearing();

		zxing.IsAnalyzing = true;
		zxing.IsScanning = true;
		zxing.Options = new MobileBarcodeScanningOptions
		{
			PossibleFormats = new List<ZXing.BarcodeFormat>() { ZXing.BarcodeFormat.QR_CODE },
			//DelayBetweenContinuousScans = 20,
			//DelayBetweenAnalyzingFrames = 20,
			//DisableAutofocus = false,
			//AutoRotate = false,
			//TryHarder = false,
			//TryInverted = false,
			//UseFrontCameraIfAvailable = false,
			//AssumeGS1 = true,
			//UseNativeScanning = true
		};
	}

	protected override void OnDisappearing()
	{
		zxing.IsScanning = false;

		base.OnDisappearing();
	}

	private void zxing_OnScanResult(ZXing.Result result)
	{
		zxing.IsAnalyzing = false;

		Device.BeginInvokeOnMainThread(async () =>
		{
			Console.WriteLine("QRPAGE | " + result.Text + " " + result.BarcodeFormat);
			await Navigation.PushAsync(new PageResult(result.Text));
			await DisplayAlert("Qr scan result", result.Text, "OK");
		});
	}

	private void overlay_FlashButtonClicked(Button sender, EventArgs e)
	{
		zxing.IsTorchOn = !zxing.IsTorchOn;
	}
}
```

iOS version of my iPhone7 13.3.1
Xamarin.Forms 4.8
Xamarin.Essentials 1.5 
ZXing.Net.Xamarin & ZXing.Net.Xamarin.Forms 2.9.9--date20200930-0111.git-0b9e2a3

Any suggestions?

**Comment by knocte** [comment]
> Qr scan and the flash command don't work in iOS

What does `don't work` exactly mean?

> Xamarin.Essentials 1.5

ZXing.Net.Xamarin depends on DotNetEssentials, not Xamarin.Essentials. If you have both, one might be conflicting with the other, please replace.

> ZXing.Net.Xamarin & ZXing.Net.Xamarin.Forms 2.9.9--date20200930-0111.git-0b9e2a3

Did you try with ZXing.Net.Mobile and ZXing.Net.Mobile.Forms instead of ZXing.Net.Xamarin(.*)?

**Comment by AndreaGobs** [comment]
> What does don't work exactly mean?

In iOS, the event OnScanResult is never fired scanning the QR code with the camera. The same code works in Android. 
Debugging, the console shows only _Too soon between frames_, like in the issue [here](https://github.com/Redth/ZXing.Net.Mobile/issues/892)
For the torch I found this [workaround](https://github.com/Redth/ZXing.Net.Mobile/issues/929#issuecomment-675396084)

> ZXing.Net.Xamarin depends on DotNetEssentials, not Xamarin.Essentials. If you have both, one might be conflicting with the other, please replace.

I tried with both Xamarin.Essentials and DotNetEssentials, never together

> Did you try with ZXing.Net.Mobile and ZXing.Net.Mobile.Forms instead of ZXing.Net.Xamarin(.*)?

Yes, before trying with ZXing.Net.Xamarin and ZXing.Net.Xamarin.Forms, but with no result

**Comment by knocte** [comment]
> Yes, before trying with ZXing.Net.Xamarin and ZXing.Net.Xamarin.Forms, but with no result

Then why are you filing this bug here? This is a very specific fork that just adds GTK support (no more differences). Please file a bug in ZXing.Net.Mobile.

> For the torch I found this workaround

Please write a comment on that issue to say that it works for you. The more info the maintainer has, the better. The more comments he receives, the better (at some point he might take action...).

>  like in the issue here

Write a comment on that issue saying that you're also affected.
