### ISSUE TITLE
Zxing problem with XCT Cameraview and Popup

### ISSUE THREAD

**Issue by vankraster** [nblockchain/ZXing.Net.Xamarin#7]
Hi,
If you create a page with Zxing then you redirect to a new page where you are using XCT CameraView and inside that page you are trying to display an alert ( with XCT popup ) then the camera blocks and sometimes the app blocks with this error:
 

> ZXing.Net.Mobile] Selected Resolution: 800x600
> [libc] Access denied finding property "vendor.camera.aux.packagelist"
> [ZXing.Net.Mobile] Changing Camera Orientation to: 90
> [System.err] java.lang.IllegalStateException: Session has been closed; further changes are illegal.[System.err]     at android.hardware.camera2.impl.CameraCaptureSessionImpl.checkNotClosed(CameraCaptureSessionImpl.java:835)[System.err]     at android.hardware.camera2.impl.CameraCaptureSessionImpl.stopRepeating(CameraCaptureSessionImpl.java:403)[System.err]     at crc642e1c7a98bdb5c44a.CameraStateListener.n_onDisconnected(Native Method)[System.err]     at crc642e1c7a98bdb5c44a.CameraStateListener.onDisconnected(CameraStateListener.java:40)[System.err]     at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:247)[System.err]     at android.os.Handler.handleCallback(Handler.java:883)[System.err]     at android.os.Handler.dispatchMessage(Handler.java:100)[System.err]     at android.os.Looper.loop(Looper.java:214)[System.err]     at android.os.HandlerThread.run(HandlerThread.java:67)
> [0:] CameraView: Error close device
> ErrorMessage: Session has been closed; further changes are illegal.

But if I don't pass by the page with ZXing and I am displaying the camera and the popup it all works perfectly. 
The error occurs right after I close the popup :
`popupPage.Dismiss(""); 
`

**Comment by knocte** [comment]
Is this also a bug in ZXing.Net.Mobile?

**Comment by vankraster** [comment]
I am using only ZXing.Net.Mobile  And  ZXing.Net.Mobile.Forms  because it is a Xamarin Forms Application using Shell but I have already tried on a Navigation Page and it has the same error.
When I refer to XCT I mean Xamarin Control Toolkit :)

**Comment by knocte** [comment]
> I am using only ZXing.Net.Mobile And ZXing.Net.Mobile.Forms 

Then why are you reporting the bug in ZXing.Net.Xamarin instead of ZXing.Net.Mobile?

**Comment by vankraster** [comment]
Sorry I will post there.

**Comment by knocte** [comment]
No worries.
